spring.application.name=microservicio-productos
spring.datasource.url=jdbc:oracle:thin:@a8qye6ta3deuch8t_high?TNS_ADMIN=/app/wallet
#spring.datasource.url=jdbc:oracle:thin:@a8qye6ta3deuch8t_high?TNS_ADMIN=C:/Ingenieria/DSY2205/Exp1_S2/Wallet_A8QYE6TA3DEUCH8T
spring.datasource.username=BDT_BIBLIOTECA
spring.datasource.password=Biblioteca._BDs1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

server.port=8082